### ISSUE TITLE
Gem falling down an extra box

### ISSUE THREAD

**Issue by tkolenbrander** [tkolenbrander/Bejeweld-Group33#16]
**Actions performed**
1. A gem is selected, such that it can make a move with the south adjacent gem.
2. The south adjacent gem is clicked.

**Expected result**
First the two gems switch position.
Then the chain disappears.
The gem that has been switched will fall down one box.

**Actual result**
First the two gems switch position.
Then the chain disappears.
The gem that has been switched **falls down two boxes**, colliding with another gem and leaving an empty box.

**Possible cause**
No clue.

**Comment by breijm** [comment]
See issue #15

**Comment by rubenvrolijk** [comment]
See issue #17
