### ISSUE TITLE
Selected gem moves down one position too far.

### ISSUE THREAD

**Issue by bvobart** [tkolenbrander/Bejeweld-Group33#17]
**Actions performed**
1. Find a situation like in one of the schemes below (or mirrored). These are extremely common.
`X - -`
`Y X X`
or
`- X -`
`X Y X`
Where the X's are gems of the same colour, the -'s are gems whose type does not matter and the Y is a gem of a different colour than X.
2. Switch the top-most X with the Y below it to create a chain. It does not matter in which order the two are selected.

**Expected result**
First, X and Y switch position. Then the created chain disappears and the gems that were above the created chain all move down a single level. Newly generated gems to fill in the empty cells at the top of the board, fall down into their respective positions from above the board.

**Actual result**
First, X and Y switch position. Then the created chain disappears and the gems that were above the created chain all move down a single level, except for Y, which for some reason moves down two squares. New gems fall down correctly.

**Possible cause**
Inspection of the list of key values in the key frames shows that none of the images representing the gems on the board are instructed to move down two cells. Perhaps it is due to the way JavaFX handles animations?

**Comment by breijm** [comment]
See #15, I suspect this is the same issue. Incorrect end positions for the animations seems to be causing this as well. Minimally I advise you to check how the positions of the image views change as swaps are made.

**Comment by rubenvrolijk** [comment]
Fixed by removing the usage of LayoutX and LayoutY to initially position the imageviews. Now the regular x and y properties are initialized, which are also used for the animations themselves. This creates consistency in the imageviews and fixes these problems.
